version: '3.9'

services:
  app:
    image: ghcr.io/iamtakagi/shadowban-alerts
    container_name: shadowban-alerts
    volumes:
      - type: bind
        source: './crontab'
        target: '/app/crontab'
      - type: bind
        source: './ShadowbanAlerts.json'
        target: '/app/ShadowbanAlerts.json'
    environment:
      - TZ=Asia/Tokyo
      - SCREEN_NAMES=@yousuck2020,@kskgroup2017
      - WEBHOOK_URL=https://discord.com/api/webhooks/xxx/xxx
